<template>
  <v-container>
    <v-row>
      <v-col cols="3">
        <v-btn
          color="#496541"
          class="even-buttons"
          @click="showNegativeTests()"
          >
          Negative Tests per State
          </v-btn>
      </v-col>
      <v-col cols="3">
        <v-btn
          color="#4D4166"
          class="even-buttons"
          @click="showDeathToll()"
        >
          Death Toll per State
        </v-btn>

      </v-col>
      <v-col cols="3">
         <v-btn
          color='#75474E'
          class="even-buttons"
          @click="showCaseCount()"
        >
          Case count per State
        </v-btn>

      </v-col>
      <v-col cols="3"> 
        <v-btn
          color="#662B28" 
          class="even-buttons"
          @click="showDeathRate()"
        >
          Death Rate per State
        </v-btn>
      </v-col>
    </v-row>
    <v-row>
      <transition name="slide" mode="out-in">
        <component v-bind:is="view"></component>
      </transition>
    </v-row>
  </v-container>
</template>

<script>
import USCasesChart from "@/components/geo_charts/USCasesChart.vue"
import USDeathRate from "@/components/geo_charts/USDeathRate.vue"
import USDeathToll from "@/components/geo_charts/USDeathToll.vue"
import USNegativeTests from "@/components/geo_charts/USNegativeTestsPerState.vue"
import {mapActions} from "vuex"
export default {
  data() {
    return {
      view: "us-negative-tests"
    }
  },
  methods: {
    ...mapActions(['fetchCases']),
    showDeathRate: function()  {
      this.view = 'us-death-rate'
    },

    showCaseCount: function() {
      this.view = 'us-cases-chart'
    },

    showDeathToll: function() {
      this.view = 'us-death-toll'
    },

    showNegativeTests: function() {
      this.view = 'us-negative-tests'
    },




  },
  components: {
    'us-cases-chart': USCasesChart,
    'us-death-rate': USDeathRate,
    'us-death-toll': USDeathToll,
    'us-negative-tests': USNegativeTests
  },
  created() {
    this.fetchCases()
  }

}

</script>


<style>

.slide-out-right {
    -webkit-animation: slide-out-right 0.5s cubic-bezier(0.895, 0.030, 0.685, 0.220) both;
            animation: slide-out-right 0.5s cubic-bezier(0.895, 0.030, 0.685, 0.220) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-4-14 5:21:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-right
 * ----------------------------------------
 */
  @-webkit-keyframes slide-out-right {
    0% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateX(1000px);
              transform: translateX(1000px);
      opacity: 0;
    }
  }
  @keyframes slide-out-right {
    0% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateX(1000px);
              transform: translateX(1000px);
      opacity: 0;
    }
  }

  .slide-in-right {
    -webkit-animation: slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
            animation: slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-4-14 5:58:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

.component-fade-enter-active, .component-fade-leave-active {
  transition: opacity .3s ease;
}
.component-fade-enter, .component-fade-leave-to
/* .component-fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}


.slide-leave-active,
.slide-enter-active {
  transition: 0.5s;
}
.slide-enter {
  transform: translate(300%, 0);
}
.slide-leave-to {
  transform: translate(-300%, 0);
}


.even-buttons {
  display: flex;
  width: 100%;
}
</style>