<template>
  <v-container fluid class="content-background">
    <div class="form-contain">
           <v-row>
             <v-col>
                <div data-aos="fade-right" data-aos-duration=800 class="descriptors">
                  <ExpertsDescription></ExpertsDescription>
                </div>
             </v-col>
           </v-row>
            <v-row>
              <v-col>
                <div data-aos="fade-left" data-aos-duration=800 class="descriptors">
                  <transition name="slide" mode="out-in">
                    <component v-bind:is="getShowForm ? 'ExpertForm' : 'ExpertList'" :class="{'increase_form_size' : getShowForm}"></component>
                  </transition>
                  <!-- <ExpertList></ExpertList> -->
                </div>

              </v-col>
        </v-row>
    </div>
  </v-container>
</template>

<script>
import ExpertList from "@/components/experts/ExpertList.vue"
import ExpertsDescription from "@/components/experts/ExpertsDescription.vue"
import ExpertForm from "@/components/experts/ExpertForm.vue"
import {mapGetters} from "vuex"

export default {
  name:'Experts',
  data() {
    return {
      // view: ExpertTable,
      show_form: false,
      // slide_out_class: false
    }
  },
  components: {
    ExpertList,
    ExpertsDescription,
    ExpertForm
  },
  computed: {
    ...mapGetters(["getShowForm"])
  }
  }

</script>

<style lang="scss" scoped>
  @import url('https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap');
  // $successColor: #3BB873;
  
  .form-contain {
    max-width: 90%;
    // max-height: 300px;
    /* padding-left: 5%;
    margin-left: 5%; */
    /* justify-content: space-between; */
    /* align-items: center; */
  }
  .content-background {
      min-width:100%;
			/* padding-left:-5%;
			margin-left:-5%;  */
      // max-height: 0%;
      display: flex;
      justify-content: center;
      align-items: center;
  }

  .slide-out-right {
    -webkit-animation: slide-out-right 0.5s cubic-bezier(0.895, 0.030, 0.685, 0.220) both;
            animation: slide-out-right 0.5s cubic-bezier(0.895, 0.030, 0.685, 0.220) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-4-14 5:21:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-right
 * ----------------------------------------
 */
  @-webkit-keyframes slide-out-right {
    0% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateX(1000px);
              transform: translateX(1000px);
      opacity: 0;
    }
  }
  @keyframes slide-out-right {
    0% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateX(1000px);
              transform: translateX(1000px);
      opacity: 0;
    }
  }

  .slide-in-right {
    -webkit-animation: slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
            animation: slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2020-4-14 5:58:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

.component-fade-enter-active, .component-fade-leave-active {
  transition: opacity .3s ease;
}
.component-fade-enter, .component-fade-leave-to
/* .component-fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}


.slide-leave-active,
.slide-enter-active {
  transition: 0.5s;
}
.slide-enter {
  transform: translate(150%, 0);
}
.slide-leave-to {
  transform: translate(-150%, 0);
}
</style>